name: Kubescape 

on:
  push:
    branches: [ master ]
 
jobs:
  nsa-security-check:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install Kubescape
        run: curl -s https://raw.githubusercontent.com/armosec/kubescape/master/install.sh | /bin/bash
        
      - name: Scan YAML files
        run: kubescape scan framework nsa -t 10 *.yaml 
        
      - name: Notify slack success
        if: success()
        env:
          SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
          uses: Discontract/github-action-slack-notify-deployment@v1
        with:
          channel: github-actions-alerting
          channel_id: C03BTFPRZKJ
          status: SUCCESS
          color: good

      - name: Notify slack fail
        if: failure()
        env:
          SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
        uses: Discontract/github-action-slack-notify-deployment@v1
        with:
          channel: github-actionis-alerting
          channel_id: C03BTFPRZKJ
          status: FAILED
          color: danger
  
