name: Kubescape 

on:
  push:
    branches: [ master ]
 
jobs:
  nsa-security-check:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install Kubescape
        run: curl -s https://raw.githubusercontent.com/armosec/kubescape/master/install.sh | /bin/bash
        
      - name: Scan YAML files
        run: kubescape scan framework nsa *.yaml --submit --account=d31337ea-0e0c-495c-a662-3bc7ab4d9883
        
  
